# Generated by Django 3.1 on 2020-09-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_auto_20200910_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='stapas',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
