# Generated by Django 3.1 on 2020-09-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_database_stapas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='pfacepas',
            new_name='facepas',
        ),
    ]
